Repository CycloneDX/cyclonedx-node-yarn, pull requests merged in 2024-11, with the labels that each got.

#197 chore: pin `flict==2.1.14`
  .github/workflows/nodejs.yml
Labels: chore

#200 chore(ci): dont upgrade yarn unexpectedly
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
Labels: bug, CT, chore, build process

#199 Switch to a TypeScript version that is compatible with the used ESLint version.
  .github/workflows/nodejs.yml
  package.json
Labels: QA, DeveloperExperience

#211 chore: disable dependabot
  .github/dependabot.yml
Labels: chore

#216 chore: revisit release process
  .github/workflows/release.yml
Labels: chore, build process

#220 chore(deps): remove dep `packageurl-js`
  HISTORY.md
  package.json
  src/builders.ts
Labels: dependencies
